### PR TITLE
Doplarr Arm64 supported docker image

### LINKED ISSUE #137: Arm64 docker support
Hello, 
As straight forward as it sound, 
can you please build arm64 images for doplarr? 
Its perfect to run on my raspberrypi and i can;t because of that. 
Thanks!!!

### PR DESCRIPTION
**Pull request by AvihaiZiv**
with this Dockerfile you should be able to use **docker buildx** to build multi-arch image (amd64/arm64),

I also added the build of the jar inside the dockerfile, feel free to remove it you deem it unneeded, 
i think it could add a value though.
overall image size went up a by 20mb or so, nothing dramatic.
Closes #137

### CODE REVIEW

**Comment by kiranshila** [comment]
Looks great! Did you test it out? I think the CMD path may be wrong because there's no app dir anymore, right?

**Comment by AvihaiZiv** [comment]
> Looks great! Did you test it out? I think the CMD path may be wrong because there's no app dir anymore, right?
> 

Yes it works fine, there is still /app dir,
As WORKDIR creates the folder and cd to it

**Comment by kiranshila** [comment]
Ah great! Thanks for you help!

**Comment by kiranshila** [comment]
Look like some things didn't work in CI, I'll take a look more closely tomorrow.

**Comment by AvihaiZiv** [comment]
if it helps, 
I ran the the docker build from the root of the project,
with this command
docker build . -f docker/Dockerfile  -t \<image\>:\<tag\> 

Also for multiarch build 
You need to use docker buildx as it can emulate the arm64 env

you will need to setup a build container first

with:

docker buildx create --use

Afterwards you can build the multiarch image like so:

docker buildx build . -f docker/Dockerfile --platform linux/amd64,linux/arm64 -t \<image\>:\<tag\> --push

**Pull request merged**
